const fs = require('fs');
const path = require('path');

function walk(dir, cb) {
  fs.readdirSync(dir).forEach(f => {
    let p = path.join(dir, f);
    if (fs.statSync(p).isDirectory()) walk(p, cb); else cb(p);
  });
}

walk(path.join(__dirname, 'client', 'src'), f => {
  if(!f.endsWith('.js') && !f.endsWith('.jsx')) return;
  let code = fs.readFileSync(f, 'utf8');
  let original = code;

  // Fix string concatenation issues generated by previous script
  // Example: 'https://jomltak-andena-server-production.up.railway.app' + "/route" -> 'https://jomltak-andena-server-production.up.railway.app/route'
  code = code.replace(/'https:\/\/jomltak-andena-server-production\.up\.railway\.app'\s*\+\s*['"](\/[^'"]+)['"]/g, "'https://jomltak-andena-server-production.up.railway.app$1'");
  
  if(code !== original) {
    fs.writeFileSync(f, code);
    console.log('Fixed concatenation in', f);
  }
});
